=== Client Configuration

The _SpringBatchLightmin-Client_ tries to configure all client side properties
by using the _Spring Boot_ auto configured _Server-_, _ManagementServer-_ and _Actuator-Properties_,
excepted the _url_ of the _SpringBatchLightmin-Server_. All these properties can be overridden.

==== Lightmin Server

The _url_ is a mandatory property. The value is a comma separated list of server urls.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        url: http://localhost:8090, http://localhost:9000
----

==== API

The _api_ property gives the relative path to the server side api.
If the value is my/api and the _url_ value is http://server:8080, the client tries
to register at http://server:8080/my/api

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        #default api/applications
        api: api/application
----

==== Registration Period

The _period_ is the time in millis, the client tries to register at the servers.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        #default 10000
        period: 100
----

==== Credentials

If the client needs credentials to access the server, _username_ and _password_
 can be set via properties.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        username: username
----

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        password: password
----

==== Auto Registration

If _auto-registration_ is set to true, the client tries to register itself automatically.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        #default true
        auto-registration: true
----

==== Auto De-Registration

If _auto-deregistration_ is set to true, the client calls the server for de-registration before the shutdown.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        #default false
        auto-deregistration: false
----

==== Register Once

If _register-once_ is set to true, the client will register itself only at one server.

[source, yaml]
----
spring:
  batch:
    lightmin:
      server:
        #default true
        auto-register-once: true
----

==== Service Url

The _service-url_ is the url of client.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client.service-url: http://localhost:8080/my-app
----

==== Management Url

The _management-url_ is the management url of the client.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        management-url: http://localhost:8080/management
----

==== Health Url

The _management-url_ is the health url of the client, it is used by the server to check the status.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        health-url: http://localhost:8080/management/health
----

==== Server Port

The _server-port_ is the application port.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        server-port: 8080
----

==== Management Port

The _server-port_ is the application management port.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        management-port: 8081
----
