== Client Configuration

The _SpringBatchLightmin-Client_ tries to configure all client side properties
by using the _Spring Boot_ auto configured _Server-_, _ManagementServer-_ and _Actuator-Properties_,
excepted the _url_ of the _SpringBatchLightmin-Server_. All these properties can be overridden.

=== Core

The core properties can be changed for all clients.

==== Service Url

The _service-url_ is the url of client.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        service-url: http://localhost:8080/my-app
----

==== Management Url

The _management-url_ is the management url of the client.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        management-url: http://localhost:8080/management
----

==== Health Url

The _management-url_ is the health url of the client, it is used by the server to check the status.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        health-url: http://localhost:8080/management/health
----

==== Server Port

The _server-port_ is the application port or the external port, if the application is running inside a container e.g. docker.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        server-port: 8080
----

==== Management Port

The _server-port_ is the application management port or the external port, if the application is running inside a container e.g. docker.
If the property is not set, the server-port will be taken.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        management-port: 8081
----

==== Hostname

The _hostname_ property can be used to set the name which should be used for registration at the server.
This can be helpful when running inside a container, e.g. docker.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        hostname: my.fqdn
----

===== Publish Job Events

The _publish-job-events_ property can used to deactivate the pushes from the client to the server when a JobExecution is finished.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        #default: true
        publish-job-events: false
----

===== Credentials to access Server

If the server is secured with a username and password, the following to properties can be set on the client side.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
       server:
         username: myuser
         password: mypassword
----


=== Classic Client

The following properties can be changed for the classic client

==== Auto Registration

If _auto-registration_ is set to true, the client tries to register itself automatically.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
            #default true
            auto-registration: true
----

==== Auto De-Registration

If _auto-deregistration_ is set to true, the client calls the server for de-registration before the shutdown.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
          #default true
          auto-deregistration: false
----

==== Register Once

If _register-once_ is set to true, the client will register itself only at one server.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
          #default false
          auto-register-once: true
----

==== Registration Period

The _period_ is the time in millis, the client tries to register at the servers.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
          #default 10000
          period: 100
----

==== Lightmin Server

The _url_ is a mandatory property. The value is a comma separated list of server urls.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
          server:
            url: http://localhost:8090, http://localhost:9000
----

==== API

The _api_ property gives the relative path to the server side api.
If the value is my/api and the _url_ value is http://server:8080, the client tries
to register at http://server:8080/my/api

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        classic:
          server:
            #default api/applications
            api: api/application
----

=== Discovery Client

The following properties can be changed for the discovery client

==== Server Discovery Name

The name discovery name of the server which should be used by the _DiscoveryClient_.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        discovery:
         #default: lightmin-server
         server-discovery-name: my-server
----

==== Server Context Path

If the server has a context path, this property will be used to enhance the discovery address by the _DiscoveryClient_.

[source, yaml]
----
spring:
  batch:
    lightmin:
      client:
        discovery:
         server-context-path: /server
----

