=== Jdbc Support
For production environments, the _Spring Batch Lightmin_ also provides jdbc components, to get the _Spring Batch Job_
 meta informations from a database and to lightminApplicationRepository the _JobConfigurations_. To use a persistent way to lightminApplicationRepository your
 _JobConfigurations_, you have to install a schema of _Spring Batch Lightmin_ next to your _Spring Batch_ tables.
 The DDL scripts for various database types are located within the core-module of the _Spring Batch Lightmin_.

==== Properties

In order to set the table prefix for the _Spring Batch_ database schema, the _spring.batch.lightmin.repository-table-prefix_-property has to placed into your application.properties. The default value is _BATCH__. The tables of the _Spring Batch Lightmin_ configuration are fully cofigurable via properties.
The _Spring Batch Lightmin_ configuration tries to create _Jdbc_-components, if a bean of type _DataSource_ is
available within the _Spring Context_. If an other _DataSource_ than the default one, with the name _dataSource_,
the properties _*.data-source-name_ for _Lightmin_ and _*.batch-data-source-name_ for
_Spring Batch_ will override the defaults.

[source, yaml]
----
spring:
  batch:
    lightmin:
      #Set the table prefix for Spring Batch tables, default BATCH_
      repository-table-prefix: MY_BATCH_PREFIX
      #Table name of the Spring Batch Lightmin Configuration, default BATCH_JOB_CONFIGURATION
      job-configuration-table-name: BATCH_JOB_CONFIGURATION
      #Table name of the Spring Batch Lightmin Configuration values, default = BATCH_JOB_CONFIGURATION_VALUE
      job-configuration-value-table-name: BATCH_JOB_CONFIGURATION_VALUE
      #Table name of the Spring Batch Lightmin Configuration Job Parameters, default = BATCH_JOB_CONFIGURATION_PARAMETERS
      job-configuration-parameter-table-name: BATCH_JOB_CONFIGURATION_PARAMETERS
      #default jdbc
      batch-repository-type: jdbc
      #default jdbc
      lightmin-repository-type: jdbc
      #default dataSource
      data-source-name: dataSource
      #default dataSource
      batch-data-source-name: dataSource
      #The value for a database schema, e.g. for postgres, default value=null
      database-schema: my_schema
----
