=== Jdbc Support
For production environments, the _Spring Batch Lightmin_ also provides jdbc components, to get the _Spring Batch Job_
 meta informations from a database and to lightminApplicationRepository the _JobConfigurations_. To use a persistent way to lightminApplicationRepository your
 _JobConfigurations_, you have to install a schema of _Spring Batch Lightmin_ next to your _Spring Batch_ tables.
 The DDL scripts for various database types are located within the core-module of the _Spring Batch Lightmin_.

==== Properties

If you have to use a different table prefix for the Spring Batch database schema and the job configuration database
schema, you have to set the _*-table-prefix_ properties in your application.properties. The default value is _BATCH__.
The _Spring Batch Lightmin_ configuration tries to create _Jdbc_-components, if a bean of type _DataSource_ is
available within the _Spring Context_. If an other _DataSource_ than the default one, with the name _dataSource_,
the properties _*.data-source-name_ for _Lightmin_ and _*.batch-data-source-name_ for
_Spring Batch_ will override the defaults.

[source, java]
----
#Set the table prefix for Spring Batch tables, default BATCH_
spring.batch.lightmin.repository-table-prefix=MY_BATCH_PREFIX
#Set the table prefix for Spring Batch Lightmin configuration tables, default BATCH__
spring.batch.lightmin.configuration-table-prefix=MY_BATCH_PREFIX_
#default jdbc
spring.batch.lightmin.batch-repository-type=jdbc
#default jdbc
spring.batch.lightmin.lightmin-repository-type=jdbc
#default dataSource
spring.batch.lightmin.data-source-name=dataSource
#default dataSource
spring.batch.lightmin.batch-data-source-name=dataSource
----
