== Job Configurations

A job Configuration contains properties, which describes how a job should be launched by _Spring Batch Lightmin_.

=== Anatomy of a Job Configuration

[source,java]
----
public class JobConfiguration extends AbstractConfiguration {

	private Long jobConfigurationId;
	private String jobName;
	private JobSchedulerConfiguration jobSchedulerConfiguration;
	private JobListenerConfiguration jobListenerConfiguration;
	private Map<String, Object> jobParameters;
	private JobIncrementer jobIncrementer;

}
----

==== Properties

===== Job Configuration Id
The _jobConfigurationId_ is a technical id to make the configuration unique.

===== Job Name
The _jobName_ is the name of _Spring Batch Job_ where the configuration belongs to.

===== Job Parameters
The _jobParameters_ are keys and values, which will passed to the _JobLauncher_, when a instance of a _Spring Batch
Job_ will be triggered by a _JobConfiguration_. The key describes the type of the parameter. Following types are
currently supported

* String
* Long
* Double
* Date

===== Job Incrementer
The _jobIncrementer_ is a job parameter which will be added to existing job parameters. This incrementer can be used to
trigger a new _JobInstance_ of a _Job_.

[source,java]
----
public enum JobIncrementer {

    DATE("DATE_INCREMENTER"),
    NONE("NONE");
}
----

===== Job Scheduler Configuration

The _JobSchedulerConfiguration_ determines, in which way a _Job_ should be launched.

[source, java]
----
public class JobSchedulerConfiguration extends AbstractConfiguration {

    private JobSchedulerType jobSchedulerType;
    private String cronExpression;
    private Long initialDelay;
    private Long fixedDelay;
    private TaskExecutorType taskExecutorType;
    private String beanName;
    private SchedulerStatus schedulerStatus;
}
----

====== JobSchedulerType

The JobSchedulerType determines, if the trigger is a CRON expression or by periods.

[source, java]
----
public enum JobSchedulerType {
    CRON(1L),
    PERIOD(2L);
}
----

====== cronExpression

It has to be not null and a regular CRON expression, if the _JobSchedulerType_ is set to _CRON_.
It has to be null, if the _JobSchedulerType_ is equal to _PERIOD_.

====== initial- & fixedDelay

Both properties must not be null or negative, if the _JobSchedulerType_ is set to _PERIOD_.
The _initialDelay_ configures the delay of the first launched after initialization and the
_fixedDelay the_ the period of a relaunch. Both values have to be null, if the _JobSchedulerType_ is equal to _CRON_.

====== TaskExecutorType

The _TaskExecutorType_ determines, if the launch of a _Job_ should be synchronously or asynchronously.
If the value is set to _SYNCHRONOUS_, the task executor will wait, until the previous run is
finished. On _ASYNCHRONOUS_ mode, the job will be launched, if the _CRON_ or _PERIOD_ trigger fires.

[source,java]
----
public enum TaskExecutorType {
    SYNCHRONOUS("SYNCHRONOUS", 1L),
    ASYNCHRONOUS("ASYNCHRONOUS", 2L);
}
----

====== beanName

The name of spring bean.

====== SchedulerStatus

The _SchedulerStatus_ represents the current status of scheduler of the
_JobConfiguration_.

[source,java]
----
public enum SchedulerStatus {
    INITIALIZED("INITIALIZED"),
    RUNNING("RUNNING"),
    STOPPED("STOPPED"),
    IN_TERMINATION("IN TERMINATION");
----

===== Job Listener Configuration

The _Job Listner Configurations_ can be registered, to listen for events and triggers a job.

[source, java]
----
public class JobListenerConfiguration extends AbstractConfiguration {

    private JobListenerType jobListenerType;
    private String sourceFolder;
    private String filePattern;
    private Long pollerPeriod;
    private String beanName;
    private ListenerStatus listenerStatus;
    private TaskExecutorType taskExecutorType;
----

====== Job Listener Type

[source,java]
----
public enum JobListenerType {

    LOCAL_FOLDER_LISTENER(1L);
}
----

* LOCAL FOLDER LISTENER

If the _LOCAL FOLDER LISTENER_ event is fired, the absolut path to the file will be passed as _Job Parameter_ with
the name *_fileSource_* to the _Job Launcher_.

====== Source Folder

The file system folder, the listener should be registered for

====== File Pattern

Ant based pattern, to filter files, which should be used for the event.

====== Poller Period

====== Bean Name

The name of spring bean.

====== Listener Status

The _Listener Status_ indicates the current status of the Listener Configuration

[source, java]
----
public enum ListenerStatus {

    ACTIVE("ACTIVE"),
    STOPPED("STOPPED");
}
----


====== Task Executor

The _TaskExecutorType_ determines, if the launch of a _Job_ should be synchronously or asynchronously.
If the value is set to _SYNCHRONOUS_, the task executor will wait, until the previous run is
finished. On _ASYNCHRONOUS_ mode, the job will be launched, if a new event occurs.

[source,java]
----
public enum TaskExecutorType {
    SYNCHRONOUS("SYNCHRONOUS", 1L),
    ASYNCHRONOUS("ASYNCHRONOUS", 2L);
}
----


=== JobConfiguration Repository

The _JobConfigurationRepository_ describes an interface, to manage _JobConfigurations_.
The current version provides three implementations, the _JdbcJobConfigurationRepository_, _RemoteJobConfigurationRepository_ and the _MapJobConfigurationRepository_.

[source, java]
----

public interface JobConfigurationRepository {

    JobConfiguration getJobConfiguration(Long jobConfigurationId, String applicationName) throws NoSuchJobConfigurationException;

    Collection<JobConfiguration> getJobConfigurations(String jobName, String applicationName) throws NoSuchJobException, NoSuchJobConfigurationException;

    JobConfiguration add(JobConfiguration jobConfiguration, String applicationName);

    JobConfiguration update(JobConfiguration jobConfiguration, String applicationName) throws NoSuchJobConfigurationException;

    void delete(JobConfiguration jobConfiguration, String applicationName) throws NoSuchJobConfigurationException;

    Collection<JobConfiguration> getAllJobConfigurations(String applicationName);

    Collection<JobConfiguration> getAllJobConfigurationsByJobNames(Collection<String> jobNames, String applicationName);

----

==== JdbcJobConfigurationRepository

The _JdbcJobConfigurationRepository_ stores the _JobConfiguration_ within a relational database.
In order to use the jdbc version, a ddl schema has to be installed.
Schemas for various providers are locate within the core jar.

===== H2 Schema example

[source, sql]
----
CREATE TABLE BATCH_JOB_CONFIGURATION (
  job_configuration_id   NUMERIC IDENTITY PRIMARY KEY NOT NULL,
  application_name       VARCHAR(255)                 NOT NULL,
  job_name               VARCHAR(255)                 NOT NULL,
  job_incrementer        VARCHAR(255),
  job_configuration_type INT                          NOT NULL
);

CREATE TABLE BATCH_JOB_CONFIGURATION_VALUE (
  id                   NUMERIC IDENTITY PRIMARY KEY NOT NULL,
  job_configuration_id NUMERIC                      NOT NULL,
  value_key            VARCHAR(255)                 NOT NULL,
  configuration_value  VARCHAR(255),
  FOREIGN KEY (job_configuration_id) REFERENCES BATCH_JOB_CONFIGURATION (job_configuration_id)
);


CREATE TABLE BATCH_JOB_CONFIGURATION_PARAMETERS (
  id                   NUMERIC IDENTITY PRIMARY KEY NOT NULL,
  job_configuration_id NUMERIC                      NOT NULL,
  parameter_name       VARCHAR(255)                 NOT NULL,
  parameter_value      VARCHAR(255)                 NOT NULL,
  parameter_type       INT                          NOT NULL,
  FOREIGN KEY (job_configuration_id) REFERENCES BATCH_JOB_CONFIGURATION (job_configuration_id)
);

----

==== RemoteJobConfigurationRepository

The _RemoteJobConfigurationRepository_ communicates with an external _repository server_ via _REST API_.

==== MapJobConfigurationRepository

The _MapJobConfigurationRepository_ stores the _JobConfigurations_ within a map.
If the application will be restarted, all stored _JobConfigurations_ will be lost.
