DROP TABLE IF EXISTS BATCH_JOB_SCHEDULER_CONFIGURATION;
DROP TABLE IF EXISTS BATCH_JOB_LISTENER_CONFIGURATION;
DROP TABLE IF EXISTS BATCH_JOB_CONFIGURATION_PARAMETERS;
DROP TABLE IF EXISTS BATCH_JOB_CONFIGURATION;