{
 "title": "Spring Batch Lightmin Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(APPLICATION_NAME)" },
   {
    "name": "jobname",
    "label": "Job Name",
    "query": "spring_batch_job_seconds_max{APPLICATION_NAME=~\"$service\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<br>\n<h1>Job Information</h1>\n\n\n\n\n\n"
  },
  {
   "title": "Service Job Count - SUCCESFUL",
   "type": "singlestat",
   "description": "Displays the total Job execution Count",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_batch_job_seconds_count{APPLICATION_NAME=~\"$service\",status=\"COMPLETED\"})"
    }
   ]
  },
  {
   "title": "Statusmap Batch Jobs per Service",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "{__name__=~\"lightmin_client_job_status\",APPLICATION_NAME=~\"$service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Service Job Count - FAILED",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(spring_batch_job_seconds_count{APPLICATION_NAME=~\"$service\",status=\"FAILED\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "content": "<br>\n<h1>Last Job Execution: $jobname</h1>\n\n\n\n\n\n"
  },
  {
   "title": "Last Item Write - $jobname",
   "type": "graph",
   "description": "This diagram shows us the last successful item write from the selected Job",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lightmin_client_step_execution_data_item_write{status=\"COMPLETED\", jobname=\"$jobname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Last Item Read - $jobname",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lightmin_client_step_execution_data_item_read{status=\"COMPLETED\", jobname=\"$jobname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Job Count - $jobname - SUCCESFUL",
   "type": "singlestat",
   "description": "Displays the total Job execution Count",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "spring_batch_job_seconds_count{name=\"$jobname\", status=\"COMPLETED\"}"
    }
   ]
  },
  {
   "title": "Job Count - $jobname - FAILED",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "spring_batch_job_seconds_count{name=\"$jobname\", status=\"FAILED\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
   "content": "<br>\n<h1>Job Execution Data: $jobname</h1>\n\n\n\n\n\n"
  },
  {
   "title": "Data of Job: $jobname",
   "type": "graph",
   "description": "This is a metric which collects Step Data per Job and displays them in one Graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (spring_batch_item_read_seconds_count{job_name=\"$jobname\"})",
     "legendFormat": "Items read"
    },
    {
     "expr": "sum (spring_batch_item_process_seconds_count{job_name=\"$jobname\"})",
     "legendFormat": "Items Processed"
    }
   ]
  },
  {
   "title": "Writes of Steps: $jobname",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_batch_chunk_write_seconds_count{job_name=\"$jobname\"}",
     "legendFormat": "Chunk Writes: {{step_name}}"
    }
   ]
  },
  {
   "title": "Job Execution Duration - $jobname",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_batch_job_seconds_max{name=\"$jobname\"}",
     "legendFormat": "{{name}} Execution time "
    },
    {
     "expr": "spring_batch_step_seconds_max{job_name=\"$jobname\"}",
     "legendFormat": "{{job_name}} -> {{name}}"
    }
   ]
  }
 ]
}